#!/bin/bash
# Usage: tmux-multi-ssh user@host00{1,2,3,4}

tmux send-keys "ssh $1" C-m
shift

for i in $*; do
  tmux split-window
  tmux select-layout tiled
  tmux send-keys "ssh $i" C-m
done

tmux select-pane -t 0
